jobs:
  include:
  - name: gcc, xeinal, pg 9.5 as service
    dist: xenial
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-client-9.5
        - postgresql-server-dev-9.5
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/9.5/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/9.5
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/9.5/main
    - psql --dbname test_database --file fs2pg.sql
    - psql --dbname test_database --command "SELECT f2p_hsz()"
    - psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - psql --dbname test_database --command "SELECT id2path('mf')"
    - psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
  - name: gcc, xeinal, pg 9.6 as service
    dist: xenial
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 9.6
      apt:
        packages:
        - postgresql-9.6
        - postgresql-client-9.6
        - postgresql-server-dev-9.6
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/9.6/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/9.6
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/9.6/main
    - psql --dbname test_database --file fs2pg.sql
    - psql --dbname test_database --command "SELECT f2p_hsz()"
    - psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - psql --dbname test_database --command "SELECT id2path('mf')"
    - psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
  - name: gcc, xeinal, pg 10 as service
    dist: xenial
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 10
      apt:
        packages:
        - postgresql-10
        - postgresql-client-10
        - postgresql-server-dev-10
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/10/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/10
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/10/main
    - psql --dbname test_database --file fs2pg.sql
    - psql --dbname test_database --command "SELECT f2p_hsz()"
    - psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - psql --dbname test_database --command "SELECT id2path('mf')"
    - psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
  - name: gcc, xeinal, pg 11 as service
    dist: xenial
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 11
      apt:
        packages:
        - postgresql-11
        - postgresql-client-11
        - postgresql-server-dev-11
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - PGPORT=5433 psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/11/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/11
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/11/main
    - PGPORT=5433 psql --dbname test_database --file fs2pg.sql
    - PGPORT=5433 psql --dbname test_database --command "SELECT f2p_hsz()"
    - PGPORT=5433 psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - PGPORT=5433 psql --dbname test_database --command "SELECT id2path('mf')"
    - PGPORT=5433 psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - PGPORT=5433 psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
  - name: gcc, xeinal, pg 12 as service
    dist: xenial
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 12
      apt:
        packages:
        - postgresql-12
        - postgresql-client-12
        - postgresql-server-dev-12
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - PGPORT=5433 psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/12/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/12
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/12/main
    - PGPORT=5433 psql --dbname test_database --file fs2pg.sql
    - PGPORT=5433 psql --dbname test_database --command "SELECT f2p_hsz()"
    - PGPORT=5433 psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - PGPORT=5433 psql --dbname test_database --command "SELECT id2path('mf')"
    - PGPORT=5433 psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - PGPORT=5433 psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
  - name: gcc, bionic, pg 9.5 as service
    dist: bionic
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-client-9.5
        - postgresql-server-dev-9.5
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/9.5/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/9.5
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/9.5/main
    - psql --dbname test_database --file fs2pg.sql
    - psql --dbname test_database --command "SELECT f2p_hsz()"
    - psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - psql --dbname test_database --command "SELECT id2path('mf')"
    - psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
  - name: gcc, bionic, pg 12 as service
    dist: bionic
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 12
      apt:
        packages:
        - postgresql-12
        - postgresql-client-12
        - postgresql-server-dev-12
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - ls -litha /var/run/postgresql
    - PGPORT=5433 psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo c    >> /pgdata/fs2pg/mf'
    - sudo bash -c 'echo j    >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/12/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/12
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/12/main
    - PGPORT=5433 psql --dbname test_database --file fs2pg.sql
    - PGPORT=5433 psql --dbname test_database --command "SELECT f2p_hsz()"
    - PGPORT=5433 psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - PGPORT=5433 psql --dbname test_database --command "SELECT id2path('mf')"
    - PGPORT=5433 psql --dbname test_database --command "COPY (SELECT * FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | cat
    - PGPORT=5433 psql --dbname test_database --command "COPY (SELECT line FROM f2p_txt('mf'::TEXT)) TO STDOUT WITH (FORMAT CSV)" | tee ./mf.csv
    - cmp ./mf.csv /pgdata/fs2pg/mf
