jobs:
  include:
  - name: gcc, pg 9.5 as service
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-client-9.5
        - postgresql-server-dev-9.5
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - psql --command 'CREATE DATABASE test_database'
    script:
    - pwd
    - gcc -Wall -Werror -v -o fs2pg.so -shared -fPIC -O3 fs2pg.c -I$(pg_config --includedir-server)
    - ls -lith
    - sudo mkdir -p /pgdata/fs2pg
    - sudo bash -c 'echo h    >  /pgdata/fs2pg/mf'
    - sudo bash -c 'echo 3776 >> /pgdata/fs2pg/mf'
    - ls -lith /pgdata/fs2pg/
    - sudo mkdir -p /lib/fs2pg
    - sudo chmod 755 /lib/fs2pg
    - sudo ls -litha /var/lib/postgresql/9.5/main
    - sudo ln fs2pg.so /lib/fs2pg/
    - ls -l /lib/fs2pg
    - ls -litha /var/lib/postgresql/9.5
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/9.5/main
    - psql --dbname test_database --file fs2pg.sql
    - psql --dbname test_database --command "SELECT f2p_hsz()"
    - psql --dbname test_database --command "SELECT f2p_tsz('mf')"
    - psql --dbname test_database --command "SELECT id2path('mf')"
    - psql --dbname test_database --command "SELECT * FROM f2p_txt('mf'::TEXT)"
