jobs:
  include:
  - name: gcc, pg 9.5 as service
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-client-9.5
        - postgresql-server-dev-9.5
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - psql --command 'CREATE DATABASE test_database'
    script:
    - gcc -v -o id2path.so -shared -fPIC -O3 id2path.c -I$(pg_config --includedir-server)
    - pwd
    - ls -litha /var/lib/postgresql/9.5/main
    - sudo mkdir -p /var/lib/postgresql/9.5/lib/fs2pg
    - ls -litha /var/lib/postgresql/9.5/lib/fs2pg
    - sudo ln id2path.so /var/lib/postgresql/9.5/lib/fs2pg/
    - ls -litha /var/lib/postgresql/9.5
    - ls -litha /var/run/postgresql
    - ls -litha /etc/postgresql/9.5/main
    - psql --dbname test_database --command "CREATE OR REPLACE FUNCTION id2path(TEXT) RETURNS TEXT AS '/var/lib/postgresql/9.5/lib/fs2pg/id2path', 'id2path' LANGUAGE C STRICT"
    - psql --dbname test_database --command "SELECT id2path('hw')"
    - netstat -anop | grep 5433
