jobs:
  include:
  - name: gcc, pg 9.5
    language: c
    services: docker
    sudo:     required
    script:
    - ls -lhit
    - docker build --tag fs2pg --file Dockerfile .
    - docker images
    - docker run --detatch fs2pg
    - docker ps
    - docker rm --force fs2pg
