jobs:
  include:
  - name: gcc, pg 9.5 as service
    sudo: required
    language: c
    services: postgresql
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-client-9.5
        - postgresql-server-dev-9.5
    env:
      global:
      - PGPORT=5433
      - PGUSER=postgres
    before_script:
    - psql --command 'CREATE DATABASE test_database'
    script:
    - gcc -v -o id2path.so -shared -fPIC -O3 id2path.c -I$(pg_config --includedir-server)
    - pwd
    - echo $HOME
    - mkdir $HOME/fs2pg
    - ln id2path.so $HOME/fs2pg/
    - ls -lith $HOME/fs2pg/
    - psql --dbname test_database --command "CREATE OR REPLACE FUNCTION id2path(TEXT) RETURNS TEXT AS '/home/travis/fs2pg/id2path', 'id2path' LANGUAGE C STRICT"
    - psql --dbname test_database --command "SELECT id2path('hw')"
