jobs:
  include:
  - name: gcc, xenial
    dist:     xenial
    language: c
    compiler: gcc
    script:
    - gcc --version
  - name: gcc, bionic
    dist:     bionic
    language: c
    compiler: gcc
    script:
    - gcc --version
