jobs:
  include:
  - name: gcc, pg 9.5
    language: c
    services: docker
    sudo:     required
    before_script:
    - docker build --tag fs2pg:latest --file Dockerfile .
    - docker run -d --name fs2pg fs2pg:latest
    script:
    - docker ps
    - docker exec -i fs2pg which psql
    after_script:
    - docker rm --force fs2pg
