CREATE FUNCTION id2path(TEXT) RETURNS TEXT    AS '/lib/fs2pg/fs2pg', 'id2path' LANGUAGE C STRICT;
CREATE FUNCTION f2p_hsz()     RETURNS INTEGER AS '/lib/fs2pg/fs2pg', 'f2p_hsz' LANGUAGE C STRICT;
CREATE FUNCTION f2p_tsz(TEXT) RETURNS INTEGER AS '/lib/fs2pg/fs2pg', 'f2p_tsz' LANGUAGE C STRICT;
